name: Build and run benchmarks
on:
  push:
    branches:
    - 'blackbird-benchmarks'
jobs:
  build:
    runs-on: 'ubuntu-22.04'
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '11', '17', '18']
        java_distribution: ['temurin', 'zulu', 'corretto', 'liberica']
    env:
      JAVA_OPTS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1'
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: ${{ matrix.java_distribution }}
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build
      run: ./mvnw -V -B -ff -ntp -f blackbird/benchmarks/pom.xml package
    - name: Run
      run: java -jar blackbird/benchmarks/target/benchmarks.jar -i 5 -wi 4 -r 10s
